### ISSUE TITLE
is there any way to exclude a file from folder when generating json file for indexing

### ISSUE THREAD

**Issue by sarincm** [clarketm/hugo-elasticsearch#42]
Hi
i am using this package in my hugo site.it is working fine.but now i need to exclude a file from indexing .is there any way to exclude certain files from indexing?
Thank you

**Comment by clarketm** [comment]
@sarin-citrus 

There in not an option to explicitly *exclude* a particular file or files. Albeit, the `--input` option does accept a [glob](https://www.npmjs.com/package/glob) which supports [extended regular expressions](https://www.npmjs.com/package/glob#glob-primer) which can help achieve exclusion.

This means that you can use `!(pattern1|pattern2|patternN)` to *exclude* files:

**e.g.**
```shell
$ hes \
 -i "content/**/!(file1-to-exclude|file2-to-exclude)" \
 ...
```

If this is not flexible enough for you, let me know; I am open to adding a *new* option for this if needed.
